import { ThemeProvider } from '@/components/theme-provider';
import './globals.css';
import { ApolloWrapper } from '@/components/apollo-wrapper';
import { ModeToggle } from '@/components/mode-toggle';
import { Toaster } from '@/components/ui/toaster';
import { UserAvatar } from '@/components/user-avatar';
import { cn } from '@/lib/utils';
import { Twitter } from 'lucide-react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans', weight: 'variable' });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.variable, 'scroll-smooth antialiased')}>
        <ThemeProvider attribute="class" defaultTheme="system" disableTransitionOnChange enableSystem>
          <ApolloWrapper>
            <header className="supports-backdrop-blur:bg-background/75 bg-background/90 sticky top-0 z-50 border-b p-4 backdrop-blur">
              <div className="container flex items-center justify-between">
                <Link className="-m-2 p-2 text-2xl font-bold" href="/" title="X">
                  <Twitter className="h-8 w-8" />
                </Link>
                <div className="flex items-center gap-4">
                  <ModeToggle />
                  <UserAvatar />
                </div>
              </div>
            </header>
            <main className="container grid grid-cols-12">{children}</main>
          </ApolloWrapper>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
